### ISSUE TITLE
First compile fails to run

### ISSUE THREAD

**Issue by axelson** [boydm/scenic_driver_nerves_rpi#10]
I believe there is a an issue similar to https://github.com/boydm/scenic_driver_glfw/pull/26 with this repository. The `Makefile` needs to be changed to compile into the `_build` directory instead of `priv` directly.

The failure manifests as the scenic scene not starting up and instead you just see the logs. The key failure in the logs is:
```
sh: exec: line 1: /srv/erlang/lib/scenic_driver_nerves_rpi-0.10.0/priv/scenic_driver_nerves_rpi: not found
```

**Comment by fhunleth** [comment]
@axelson Could you try out #11? I made the change to build under `_build`. I didn't see the issue that you were seeing, though, so I'm not sure it will fix it for you.

**Comment by axelson** [comment]
@fhunleth Thanks, it works :+1: great for me

**Comment by fhunleth** [comment]
Thanks for testing so quickly!

**Comment by boydm** [comment]
This should be fixed. Closing the issue...
